default_language_version:
  python: python3
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
# I want to use the ruff-check hook but it isn't released yet, so using the commit from master
  rev: v0.12.2
  hooks:
    - id: ruff-check  # isort
      args: ["--select", "I", "--fix"]
      exclude: rana_qgis_plugin/libs/.
    - id: ruff-format
      exclude: rana_qgis_plugin/libs/.
