services:
  qgis:
    build: .
    ports:
      - "7070:7070"
      - "5900:5900" # x11vnc
    tmpfs:
      - /tmp
      - /tmp/.X11-unix
    environment:
      RANA_PAK: ${RANA_PAK}
    volumes:
      - .:/tests_directory/
      - profile-dir:/root/.local/share/QGIS/QGIS3/profiles/default

volumes:
  profile-dir:
