name: pytest

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
      # - uses: pyvista/setup-headless-display-action@v3
      #   with:
      #     qt: true
      # 2️⃣ Build Docker image
      - name: Build QGIS Docker image
        run: docker compose build qgis

      # 3️⃣ Run tests headless inside container
      - name: Run e2e
        run: 
          docker compose run --rm qgis pytest -v e2e
        env:
          RANA_PAK: ${{ secrets.RANA_PAK }}
          ORG_3DI: ${{ secrets.ORG_3DI }}